{
 "title": "ZTE MC801A HyperBox 5G",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cellular Signal",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zte_signalbar" }
   ]
  },
  {
   "title": "WAN IPv4",
   "type": "stat",
   "description": "CGNAT (Carrier-Grade Network Address Translation) is a technique used by ISPs to conserve IPv4 addresses by sharing a single public IP address among multiple customers, which can limit direct inbound connections and impact certain applications or services. It is a temporary solution until the transition to IPv6, which provides a larger address space.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (wan_ipaddr)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_wifi_metrics) by (wifi_chip1_ssid1_ssid)"
    },
    {
     "expr": "max(zte_wifi_metrics) by (wifi_chip2_ssid1_ssid)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_wifi_metrics) by (wifi_onoff_state)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_wifi_metrics) by (lan_ipaddr)"
    }
   ]
  },
  {
   "title": "Network Provider",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (network_provider)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_dev_metrics) by (wa_inner_version, hardware_version)"
    }
   ]
  },
  {
   "title": "WAN IPv6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (ipv6_wan_ipaddr)"
    }
   ]
  },
  {
   "title": "WIFI Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zte_wifi_access_sta_num" }
   ]
  },
  {
   "type": "stat",
   "description": "The MSISDN (Mobile Station International Subscriber Directory Number) is a unique identifier assigned to a mobile device's phone number. It represents the phone number in a format recognized by the mobile network.\n\nThe IMEI (International Mobile Equipment Identity) is a unique identifier assigned to each mobile device. It is used to identify and track individual mobile devices on a network. The IMEI is helpful in various situations such as reporting a lost or stolen device, activating a device on a network, or for network operators to provide device-specific services and support.\n\nThe IMSI (International Mobile Subscriber Identity) on a SIM card is a unique identifier assigned to each mobile subscriber. It is used by the mobile network to identify and authenticate the user on the network.",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (msisdn, sim_imsi, imei)"
    }
   ]
  },
  {
   "title": "Cellular Signal Quality (LTE/5G)",
   "type": "timeseries",
   "description": "SINR stands for Signal-to-Interference-plus-Noise Ratio. It is a measure of the signal quality in wireless communication systems. SINR represents the ratio of the desired signal power to the combined interference and noise power. A higher SINR value indicates better signal quality and reduced interference.\n\nRSSI stands for Received Signal Strength Indicator. It measures the power level of the received signal in a wireless communication system. RSSI provides a general indication of signal strength, but it does not take into account the presence of interference or noise.\n\nRSRP stands for Reference Signal Received Power. It is a measurement of the power level of the reference signals in a Long Term Evolution (LTE) network. RSRP provides information about the strength of the serving cell's signal in relation to other signals and is used for cell selection and handover decisions.\n\nSNR stands for Signal-to-Noise Ratio. It measures the ratio of the power of the desired signal to the power of the background noise in a communication system. SNR indicates the level of signal quality and determines the system's ability to receive and interpret the desired signal accurately. A higher SNR value indicates a stronger signal relative to the noise, resulting in better communication performance.",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 4 },
   "targets": [
    { "expr": "zte_Z5g_SINR", "legendFormat": "5G SINR" },
    { "expr": "zte_Z5g_rsrp", "legendFormat": "5G RSRP" },
    { "expr": "zte_lte_rssi", "legendFormat": "LTE RSSI" },
    { "expr": "zte_lte_rsrp", "legendFormat": "LTE RSRP" },
    { "expr": "zte_lte_snr", "legendFormat": "LTE SNR" }
   ]
  },
  {
   "title": "SMS Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zte_sms_unread_num" }
   ]
  },
  {
   "title": "SPN",
   "type": "stat",
   "description": "The Service Provider Name (SPN) on a SIM card refers to the name of the network operator or service provider that the SIM card is associated with. It is essentially a label or identifier that helps users identify the network they are connected to when using their mobile devices.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (spn_name_data)"
    }
   ]
  },
  {
   "title": "Cellular Status",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "max(zte_cell_metrics) by (cell_id, wan_active_band, nr5g_pci, nr5g_action_band, ipv6_pdp_type, pdp_type, opms_wan_mode, ppp_status, network_type, lte_pci)"
    },
    { "expr": "max(zte_nr5g_action_channel)" },
    { "expr": "max(zte_wan_active_channel)" },
    { "expr": "max(zte_lte_ca_pcell_band)" },
    { "expr": "max(zte_lte_ca_scell_band)" }
   ]
  },
  {
   "title": "Device Temperatures",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zte_pm_modem_5g", "legendFormat": "5G Modem" },
    { "expr": "zte_pm_sensor_mdm", "legendFormat": "Router Board" }
   ]
  },
  {
   "title": "WAN Datarate (byte/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(zte_realtime_rx_bytes[$__rate_interval])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(zte_realtime_tx_bytes[$__rate_interval])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}